name: py313
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - notebook
  - pandas
  - numpy
  - openpyxl
  - azure-storage-blob
  - azure-identity
  - pyspark
  - databricks-cli
  - openai
  - langchain
  - chromadb
  - sentence-transformers
  - tiktoken
  - tqdm
  - python-dotenv
